site_name: GapML NLP
theme: readthedocs
repo_url: https://github.com/gapml/NLP
google_analytics: ['UA-124527631-3', 'https://gapml.github.io/NLP/']
nav:
- Home: index.md
- About: about.md
- Organization: org-os.md
- Quick Start Guide: quick-start-guide.md
- Tutorials:
    - Natural Language Processing: tutorials/natural_language_processing.md
- Specifications:
    - Splitter: specs/splitter_spec.md
    - Syntax: specs/syntax_spec.md
    - Segmentation: specs/segmentation_spec.md